name: md_to_html

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell

    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Pandoc
      run: |
        $url = "https://github.com/jgm/pandoc/releases/download/2.11.4/pandoc-2.11.4-windows-x86_64.msi"
        $output = "pandoc-installer.msi"
        Invoke-WebRequest -Uri $url -OutFile $output
        msiexec /i $output /quiet

    - name: Verify Pandoc Installation
      run: |
        $pandocPath = Get-Command pandoc -ErrorAction SilentlyContinue
        if ($null -ne $pandocPath) {
          Write-Output "Pandoc found at $($pandocPath.Source)"
        } else {
          Write-Output "Pandoc not found"
        }

    - name: Convert MD to HTML
      run: |
        Get-ChildItem -Recurse -Filter *.md | ForEach-Object {
          pandoc "$_" -o "$($_.FullName -replace '\.md$', '.html')"
        }

    - name: Commit and push
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add -A
        git commit -m "Convert MD to HTML" || echo "No changes to commit"
        git push
