name: md_to_html

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell

    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Pandoc with Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
        iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
        choco install pandoc -y

    - name: Convert MD to HTML
      run: |
        Get-ChildItem -Recurse -Filter *.md | ForEach-Object {
          pandoc $_.FullName -o "$($_.FullName -replace '\.md$', '.html')"
        }

    - name: Commit and push
      run: |
        git config user.name "Jacob Rogers"
        git config user.email "rogersair2@aol.com"
        git add -A
        git commit -m "Convert MD to HTML"
        if ($LastExitCode -ne 0) {
          Write-Output "No changes to commit"
        } else {
          git push "https://${{ secrets.GH_PAT }}@github.com/jacobrogers603/notes_md_to_web_pipeline.git"
        }

