name: md_to_html

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Convert MD to HTML
        run: |
          docker run --rm -v "${{ github.workspace }}:/data" jrog603/pandoc_installed:latest sh -c "\
            cd /data && \
            pwd && \
            ls -l && \
            find . -name '*.md' && \
            find . -name '*.md' | while IFS= read -r file; do \
              echo \"Processing \$file\"; \
              pandoc \"\$file\" --template template.html --toc --css=style.css -o \"\${file%.md}.html\"; \
            done"


      - name: Format HTML files
        run: |
          docker run --rm -v "${{ github.workspace }}:/data" jrog603/pandoc_installed:latest sh -c "cd /data && format-html"

      - name: Commit and push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "Jacob Rogers"
          git config user.email "rogersair2@aol.com"
          git add -A
          git diff --quiet && git diff --staged --quiet || echo "No changes to commit" || exit 0
          git commit -m "Convert MD to HTML"
          git remote set-url origin https://x-access-token:$GH_PAT@github.com/jacobrogers603/notes_md_to_web_pipeline.git
          git push
